version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.serenity-bdd:serenity-core
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.31
    - 2.4.1
    - 2.4.20
    - 2.4.3
    - 2.4.4
  - dependency-name: net.serenity-bdd:serenity-spring
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.31
    - 2.4.1
    - 2.4.20
    - 2.4.3
    - 2.4.4
  - dependency-name: net.serenity-bdd.maven.plugins:serenity-maven-plugin
    versions:
    - 2.3.12
    - 2.3.31
    - 2.4.1
    - 2.4.20
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.cucumber:cucumber-java
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: io.cucumber:cucumber-java8
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: io.cucumber:cucumber-junit
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
